name: Compiling and checking tests

on:
  push:
    branches-ignore : 
      - main
   
jobs:
  ubuntu-build:
    name    : Ubuntu Build
    runs-on : ubuntu-latest
    steps:
      - name : Checkout code
        uses : actions/checkout@v3

      - name : Install Dependencies
        run  : |
                sudo apt-get update 
                sudo apt-get install cppcheck 

      - name : Run CMake
        run  : |
               export CC=gcc-10 
               export CXX=g++-10 
               mkdir build  
               cd build 
               cmake .. -DCMAKE_BUILD_TYPE=Debug 

      - name : Build Project
        run  : cd build  && make 

      - name : Run Cppcheck
        run  : cppcheck --force . -ibuild/

      - name : Run CTest
        run  : cd build && ctest --verbose

  windows-build:
    name : Windows Build
    runs-on : windows-latest
    steps : 
      - name : Checkout code
        uses : actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name : Run CMake
        run  : |
                mkdir build  
                cd build 
                cmake .. 

      - name : Build Project
        run  : cd build  && msbuild ALL_BUILD.vcxproj /p:Configuration=Debug

      - name : Run CTest
        run  : cd build && ctest -C Debug --verbose

  macos-build:
    name    : MacOS Build
    runs-on : macos-latest
    steps:
      - name : Checkout code
        uses : actions/checkout@v3

      - name : Install Dependencies
        run  : |
                sudo apt-get update 
                sudo apt-get install cppcheck 

      - name : Run CMake
        run  : |
               export CC=gcc-10 
               export CXX=g++-10 
               mkdir build  
               cd build 
               cmake .. -DCMAKE_BUILD_TYPE=Debug 

      - name : Build Project
        run  : cd build  && make 

      - name : Run Cppcheck
        run  : cppcheck --force . -ibuild/

      - name : Run CTest
        run  : cd build && ctest --verbose
