name: Compiling and checking tests

on:
  push:
    branches-ignore : 
      - main
   
jobs:
  ubuntu-build:
    name    : Ubuntu Build
    runs-on : ubuntu-latest
    steps:
      - name : Checkout code
        uses : actions/checkout@v2

      - name : Install Dependencies
        run  : |
                sudo apt-get update 
                sudo apt-get install cppcheck 

      - name : Run CMake
        run  : |
               export CC=gcc-10 
               export CXX=g++-10 
               mkdir build  
               cd build 
               cmake .. -DCMAKE_BUILD_TYPE=Debug 

      - name : Build Project
        run  : cd build  && make 

      - name : Run Cppcheck
        run  : cppcheck --force . -ibuild/

      - name : Run CTest
        run  : cd build && ctest --verbose

  windows-build:
    name : Windows Build
    runs-on : windows-latest
    environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
    steps : 
      - name : Checkout code
          uses : actions/checkout@v2

        - name : Run CMake
          run  : |
                mkdir build  
                cd build 
                cmake .. -DCMAKE_BUILD_TYPE=Debug 

        - name : Build Project
          run  : cd build  && make 

        - name : Run CTest
          run  : cd build && ctest --verbose
